# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import phases_pb2 as phases__pb2


class MoonPhasesStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPhases = channel.unary_unary(
        '/phases.MoonPhases/GetPhases',
        request_serializer=phases__pb2.GetPhasesRequest.SerializeToString,
        response_deserializer=phases__pb2.GetPhasesResponse.FromString,
        )


class MoonPhasesServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPhases(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MoonPhasesServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPhases': grpc.unary_unary_rpc_method_handler(
          servicer.GetPhases,
          request_deserializer=phases__pb2.GetPhasesRequest.FromString,
          response_serializer=phases__pb2.GetPhasesResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'phases.MoonPhases', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
