# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: phases.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='phases.proto',
  package='phases',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cphases.proto\x12\x06phases\"z\n\tPhaseInfo\x12\x0c\n\x04\x43ity\x18\x01 \x01(\t\x12\x0b\n\x03Lat\x18\x02 \x01(\t\x12\x0b\n\x03Lon\x18\x03 \x01(\t\x12\x14\n\x0c\x43losestPhase\x18\x04 \x01(\t\x12\x0c\n\x04Rise\x18\x05 \x01(\t\x12\x14\n\x0cUpperTransit\x18\x06 \x01(\t\x12\x0b\n\x03Set\x18\x07 \x01(\t\"\x12\n\x10GetPhasesRequest\"9\n\x11GetPhasesResponse\x12$\n\tPhaseInfo\x18\x01 \x01(\x0b\x32\x11.phases.PhaseInfo2P\n\nMoonPhases\x12\x42\n\tGetPhases\x12\x18.phases.GetPhasesRequest\x1a\x19.phases.GetPhasesResponse\"\x00\x62\x06proto3')
)




_PHASEINFO = _descriptor.Descriptor(
  name='PhaseInfo',
  full_name='phases.PhaseInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='City', full_name='phases.PhaseInfo.City', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Lat', full_name='phases.PhaseInfo.Lat', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Lon', full_name='phases.PhaseInfo.Lon', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ClosestPhase', full_name='phases.PhaseInfo.ClosestPhase', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Rise', full_name='phases.PhaseInfo.Rise', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='UpperTransit', full_name='phases.PhaseInfo.UpperTransit', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Set', full_name='phases.PhaseInfo.Set', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=146,
)


_GETPHASESREQUEST = _descriptor.Descriptor(
  name='GetPhasesRequest',
  full_name='phases.GetPhasesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=166,
)


_GETPHASESRESPONSE = _descriptor.Descriptor(
  name='GetPhasesResponse',
  full_name='phases.GetPhasesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PhaseInfo', full_name='phases.GetPhasesResponse.PhaseInfo', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=225,
)

_GETPHASESRESPONSE.fields_by_name['PhaseInfo'].message_type = _PHASEINFO
DESCRIPTOR.message_types_by_name['PhaseInfo'] = _PHASEINFO
DESCRIPTOR.message_types_by_name['GetPhasesRequest'] = _GETPHASESREQUEST
DESCRIPTOR.message_types_by_name['GetPhasesResponse'] = _GETPHASESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PhaseInfo = _reflection.GeneratedProtocolMessageType('PhaseInfo', (_message.Message,), dict(
  DESCRIPTOR = _PHASEINFO,
  __module__ = 'phases_pb2'
  # @@protoc_insertion_point(class_scope:phases.PhaseInfo)
  ))
_sym_db.RegisterMessage(PhaseInfo)

GetPhasesRequest = _reflection.GeneratedProtocolMessageType('GetPhasesRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETPHASESREQUEST,
  __module__ = 'phases_pb2'
  # @@protoc_insertion_point(class_scope:phases.GetPhasesRequest)
  ))
_sym_db.RegisterMessage(GetPhasesRequest)

GetPhasesResponse = _reflection.GeneratedProtocolMessageType('GetPhasesResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETPHASESRESPONSE,
  __module__ = 'phases_pb2'
  # @@protoc_insertion_point(class_scope:phases.GetPhasesResponse)
  ))
_sym_db.RegisterMessage(GetPhasesResponse)



_MOONPHASES = _descriptor.ServiceDescriptor(
  name='MoonPhases',
  full_name='phases.MoonPhases',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=227,
  serialized_end=307,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPhases',
    full_name='phases.MoonPhases.GetPhases',
    index=0,
    containing_service=None,
    input_type=_GETPHASESREQUEST,
    output_type=_GETPHASESRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOONPHASES)

DESCRIPTOR.services_by_name['MoonPhases'] = _MOONPHASES

# @@protoc_insertion_point(module_scope)
